#!/usr/bin/env node
// Bench runner. Launches Electron with perf instrumentation enabled, opens a
// pre-generated vault, drives a small set of operations N times, and prints a
// summary. Optionally writes docs/bench/baseline.md.
//
// Usage:
//   node scripts/bench/run-bench.js <vault-path>:<label> [<vault-path>:<label> ...]
//
// Example:
//   node scripts/bench/run-bench.js /tmp/nl-bench-100:100 /tmp/nl-bench-1k:1k

const fs = require('fs');
const os = require('os');
const path = require('path');
const { _electron } = require('playwright');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const ITERATIONS = 5;

// Targets from docs/plans/future/plan-large-vault-performance.md, expressed at 10k notes.
// Used only to label rows in baseline.md as on/off target — this script does
// not gate or fail on a missed target.
const TARGETS_AT_10K = {
  'project.open': 2000,
  'linkgraph.rebuild': 1000,
  'file.read': 100,
  'file.write': 50,
  'search.query': 50,
  'links.backlinks': 30,
};

async function runOnce(vaultPath, label) {
  const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'nl-bench-userdata-'));
  const perfLog = path.join(userData, 'perf.log');
  fs.writeFileSync(perfLog, '');

  const electronApp = await _electron.launch({
    args: [REPO_ROOT, '--user-data-dir=' + userData, '--no-sandbox'],
    cwd: REPO_ROOT,
    env: {
      ...process.env,
      NODE_ENV: 'test',
      NOTELINER_BENCH: '1',
      NOTELINER_BENCH_LOG: perfLog,
      GIT_AUTHOR_NAME: 'Bench',
      GIT_AUTHOR_EMAIL: 'bench@example.com',
      GIT_COMMITTER_NAME: 'Bench',
      GIT_COMMITTER_EMAIL: 'bench@example.com',
    },
  });

  try {
    const window = await electronApp.firstWindow();
    await window.waitForLoadState('domcontentloaded');
    await window.waitForFunction(() => !!window.__nlTest, null, { timeout: 15000 });

    // Cold open. Times project.open + linkgraph.rebuild (nested).
    await window.evaluate((p) => window.__nlTest.openProject(p), vaultPath);

    // Pick a representative file id for repeated ops.
    const fileId = await window.evaluate(() => {
      const files = window.__nlTest.snapshot().files;
      return files[Math.floor(files.length / 2)].id;
    });
    const fileName = await window.evaluate((id) => {
      const f = window.__nlTest.snapshot().files.find(x => x.id === id);
      return f.filename;
    }, fileId);

    // Repeated operations.
    for (let i = 0; i < ITERATIONS; i++) {
      // file.read via selectFile
      await window.evaluate((id) => window.__nlTest.selectFile(id), fileId);
      // file.write — small body so we don't bloat the vault meaningfully
      await window.evaluate((iter) => window.__nlTest.writeBody('# bench iter ' + iter + '\n\nbody\n'), i);
      // search.query
      await window.evaluate(() => window.api.searchFiles('aa', {}));
      // links.backlinks
      await window.evaluate((id) => window.api.getBacklinks(id), fileId);
      // linkgraph.rebuild (warm)
      await window.evaluate(() => window.api.rebuildLinkGraph());
    }

    // Tiny pause to let any tail work flush.
    await window.waitForTimeout(50);
  } finally {
    try { await electronApp.close(); } catch { /* ignore */ }
  }

  const lines = fs.readFileSync(perfLog, 'utf-8').trim().split('\n').filter(Boolean);
  const events = lines.map((l) => JSON.parse(l));
  fs.rmSync(userData, { recursive: true, force: true });
  return { label, events };
}

function summarize(events) {
  const byOp = new Map();
  for (const e of events) {
    if (!byOp.has(e.name)) byOp.set(e.name, []);
    byOp.get(e.name).push(e.ms);
  }
  const rows = [];
  for (const [op, samples] of byOp) {
    samples.sort((a, b) => a - b);
    // Drop best+worst when >= 3 samples; report mean of remainder.
    const trimmed = samples.length >= 3 ? samples.slice(1, -1) : samples;
    const mean = trimmed.reduce((s, x) => s + x, 0) / trimmed.length;
    const min = samples[0];
    const max = samples[samples.length - 1];
    rows.push({
      op,
      n: samples.length,
      mean: Math.round(mean * 10) / 10,
      min: Math.round(min * 10) / 10,
      max: Math.round(max * 10) / 10,
    });
  }
  rows.sort((a, b) => a.op.localeCompare(b.op));
  return rows;
}

function renderConsole(label, rows) {
  process.stdout.write('\n=== ' + label + ' ===\n');
  for (const r of rows) {
    process.stdout.write(
      '  ' + r.op.padEnd(22) +
      String(r.mean + 'ms').padStart(8) + '  (n=' + r.n + ', min=' + r.min + ', max=' + r.max + ')\n'
    );
  }
}

function renderMarkdown(runs) {
  const allOps = [...new Set(runs.flatMap((r) => r.rows.map((x) => x.op)))].sort();
  let md = '# Bench Baseline\n\n';
  md += 'Measured ' + new Date().toISOString() + '.\n\n';
  md += 'Auto-generated by `scripts/bench/run-bench.js --write`. Hand-edits below the\n';
  md += '"Notes" section will be overwritten on the next run.\n\n';
  md += 'All values are mean wall-clock milliseconds, with best+worst trimmed (n=' + ITERATIONS + ' iterations per repeated op).\n';
  md += 'Cold ops (project.open) are measured once per run.\n\n';

  // Measurements table.
  md += '## Measurements\n\n';
  md += '| Operation | ' + runs.map((r) => r.label).join(' | ') + ' |\n';
  md += '|---|' + runs.map(() => '---:|').join('') + '\n';
  for (const op of allOps) {
    const cells = runs.map((run) => {
      const row = run.rows.find((r) => r.op === op);
      return row ? row.mean + 'ms' : '—';
    });
    md += '| ' + op + ' | ' + cells.join(' | ') + ' |\n';
  }

  // Targets table — compare the largest run against the documented targets.
  const largest = runs[runs.length - 1];
  if (largest) {
    md += '\n## Targets vs. ' + largest.label + '\n\n';
    md += 'Targets are sourced from `docs/plans/future/plan-large-vault-performance.md`\n';
    md += 'and expressed at 10k notes. ✅ = under target, ⚠️ = over target.\n\n';
    md += '| Operation | Target | ' + largest.label + ' | Status |\n';
    md += '|---|---:|---:|:---:|\n';
    for (const op of allOps) {
      const target = TARGETS_AT_10K[op];
      const row = largest.rows.find((r) => r.op === op);
      const actual = row ? row.mean : null;
      const targetCell = target != null ? target + 'ms' : '—';
      const actualCell = actual != null ? actual + 'ms' : '—';
      let status = '—';
      if (target != null && actual != null) {
        status = actual <= target ? '✅' : '⚠️';
      }
      md += '| ' + op + ' | ' + targetCell + ' | ' + actualCell + ' | ' + status + ' |\n';
    }
  }

  md += '\n## Notes\n\n';
  md += '- Hardware: ' + os.cpus()[0].model + ', ' + os.cpus().length + ' cores.\n';
  md += '- Platform: ' + process.platform + ' / Node ' + process.version + '.\n';
  md += '- `project.open` is cold per run and includes the nested `linkgraph.rebuild`.\n';
  md += '- Repeated ops execute against a pre-opened vault; caches are warm.\n';
  md += '- Targets are not enforced; this script never fails on a missed target.\n';
  return md;
}

async function main() {
  const args = process.argv.slice(2);
  const writeBaseline = args.includes('--write');
  const positional = args.filter((a) => !a.startsWith('--'));
  if (positional.length === 0) {
    process.stderr.write('Usage: run-bench.js <vault>:<label> [...] [--write]\n');
    process.exit(1);
  }

  const runs = [];
  for (const arg of positional) {
    const idx = arg.lastIndexOf(':');
    if (idx < 0) {
      process.stderr.write('Bad arg "' + arg + '" — expected <vault>:<label>\n');
      process.exit(1);
    }
    const vault = arg.slice(0, idx);
    const label = arg.slice(idx + 1);
    if (!fs.existsSync(vault)) {
      process.stderr.write('Vault not found: ' + vault + '\n');
      process.exit(1);
    }
    process.stdout.write('Running bench on ' + label + ' (' + vault + ')...\n');
    const t0 = Date.now();
    const { events } = await runOnce(vault, label);
    const wall = Date.now() - t0;
    const rows = summarize(events);
    runs.push({ label, rows });
    renderConsole(label, rows);
    process.stdout.write('  (run wall time: ' + wall + 'ms)\n');
  }

  if (writeBaseline) {
    const md = renderMarkdown(runs);
    const outDir = path.join(REPO_ROOT, 'docs', 'bench');
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, 'baseline.md');
    fs.writeFileSync(outPath, md);
    process.stdout.write('\nWrote ' + outPath + '\n');
  } else {
    process.stdout.write('\n(Pass --write to update docs/bench/baseline.md)\n');
  }
}

main().catch((e) => {
  process.stderr.write(String(e.stack || e) + '\n');
  process.exit(1);
});
